In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/olympic_athlete_events.csv',
    sep= ',',
    header= 0,
    usecols= ['Age', 'Height', 'Team', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal']
)

df = df.set_index(['Year', 'Season', 'Sport', 'Event'])

In [3]:
df

                                                                     Age  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball               24.0
2012 Summer Judo          Judo Men's Extra-Lightweight              23.0
1920 Summer Football      Football Men's Football                   24.0
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War               34.0
1988 Winter Speed Skating Speed Skating Women's 500 metres          21.0
...                                                                  ...
1976 Winter Luge          Luge Mixed (Men)'s Doubles                29.0
2014 Winter Ski Jumping   Ski Jumping Men's Large Hill, Individual  27.0
                          Ski Jumping Men's Large Hill, Team        27.0
1998 Winter Bobsleigh     Bobsleigh Men's Four                      30.0
2002 Winter Bobsleigh     Bobsleigh Men's Four                      34.0

                                                                    Height  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball                180.0
2012 Summer Judo          Judo Men's Extra-Lightweight               170.0
1920 Summer Football      Football Men's Football                      NaN
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War                  NaN
1988 Winter Speed Skating Speed Skating Women's 500 metres           185.0
...                                                                    ...
1976 Winter Luge          Luge Mixed (Men)'s Doubles                 179.0
2014 Winter Ski Jumping   Ski Jumping Men's Large Hill, Individual   176.0
                          Ski Jumping Men's Large Hill, Team         176.0
1998 Winter Bobsleigh     Bobsleigh Men's Four                       185.0
2002 Winter Bobsleigh     Bobsleigh Men's Four                       185.0

                                                                              Team  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball                        China
2012 Summer Judo          Judo Men's Extra-Lightweight                       China
1920 Summer Football      Football Men's Football                          Denmark
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War               Denmark/Sweden
1988 Winter Speed Skating Speed Skating Women's 500 metres             Netherlands
...                                                                            ...
1976 Winter Luge          Luge Mixed (Men)'s Doubles                      Poland-1
2014 Winter Ski Jumping   Ski Jumping Men's Large Hill, Individual          Poland
                          Ski Jumping Men's Large Hill, Team                Poland
1998 Winter Bobsleigh     Bobsleigh Men's Four                              Poland
2002 Winter Bobsleigh     Bobsleigh Men's Four                              Poland

                                                                              City  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball                    Barcelona
2012 Summer Judo          Judo Men's Extra-Lightweight                      London
1920 Summer Football      Football Men's Football                        Antwerpen
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War                        Paris
1988 Winter Speed Skating Speed Skating Women's 500 metres                 Calgary
...                                                                            ...
1976 Winter Luge          Luge Mixed (Men)'s Doubles                     Innsbruck
2014 Winter Ski Jumping   Ski Jumping Men's Large Hill, Individual           Sochi
                          Ski Jumping Men's Large Hill, Team                 Sochi
1998 Winter Bobsleigh     Bobsleigh Men's Four                              Nagano
2002 Winter Bobsleigh     Bobsleigh Men's Four                      Salt Lake City

                                                                   Medal
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball                NaN
2012 Summer Judo          Judo Men's Extra-Lightweight               NaN
1920 Summer Football      Football Men's Football                    NaN
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War               Gold
1988 Winter Speed Skating Speed Skating Women's 500 metres           NaN
...                                                                  ...
1976 Winter Luge          Luge Mixed (Men)'s Doubles                 NaN
2014 Winter Ski Jumping   Ski Jumping Men's Large Hill, Individual   NaN
                          Ski Jumping Men's Large Hill, Team         NaN
1998 Winter Bobsleigh     Bobsleigh Men's Four                       NaN
2002 Winter Bobsleigh     Bobsleigh Men's Four                       NaN

[271116 rows x 5 columns]

In [4]:
# What is the average age of winning athletes in summer games held between 1936 and 2000?

df = df.sort_index()
df.loc[(slice(1936, 2000), 'Summer'), 'Age'].mean()

np.float64(25.026883940421765)

In [5]:
df.loc[(slice(1936, 2000), 'Summer'), :]

                                                                                  Age  \
Year Season Sport            Event
1936 Summer Aeronautics      Aeronautics Mixed Aeronautics                       26.0
            Alpinism         Alpinism Mixed Alpinism                             49.0
                             Alpinism Mixed Alpinism                             43.0
            Art Competitions Art Competitions Mixed Architecture, Architectu...  47.0
                             Art Competitions Mixed Architecture, Architectu...  47.0
...                                                                               ...
2000 Summer Wrestling        Wrestling Men's Welterweight, Greco-Roman           28.0
                             Wrestling Men's Welterweight, Greco-Roman           27.0
                             Wrestling Men's Welterweight, Greco-Roman           31.0
                             Wrestling Men's Welterweight, Greco-Roman           32.0
                             Wrestling Men's Welterweight, Greco-Roman           20.0

                                                                                 Height  \
Year Season Sport            Event
1936 Summer Aeronautics      Aeronautics Mixed Aeronautics                          NaN
            Alpinism         Alpinism Mixed Alpinism                                NaN
                             Alpinism Mixed Alpinism                                NaN
            Art Competitions Art Competitions Mixed Architecture, Architectu...     NaN
                             Art Competitions Mixed Architecture, Architectu...     NaN
...                                                                                 ...
2000 Summer Wrestling        Wrestling Men's Welterweight, Greco-Roman            175.0
                             Wrestling Men's Welterweight, Greco-Roman            167.0
                             Wrestling Men's Welterweight, Greco-Roman            170.0
                             Wrestling Men's Welterweight, Greco-Roman            168.0
                             Wrestling Men's Welterweight, Greco-Roman            172.0

                                                                                          Team  \
Year Season Sport            Event
1936 Summer Aeronautics      Aeronautics Mixed Aeronautics                         Switzerland
            Alpinism         Alpinism Mixed Alpinism                               Switzerland
                             Alpinism Mixed Alpinism                               Switzerland
            Art Competitions Art Competitions Mixed Architecture, Architectu...    Netherlands
                             Art Competitions Mixed Architecture, Architectu...    Netherlands
...                                                                                        ...
2000 Summer Wrestling        Wrestling Men's Welterweight, Greco-Roman           United States
                             Wrestling Men's Welterweight, Greco-Roman             South Korea
                             Wrestling Men's Welterweight, Greco-Roman                  Poland
                             Wrestling Men's Welterweight, Greco-Roman                  France
                             Wrestling Men's Welterweight, Greco-Roman                    Iran

                                                                                   City  \
Year Season Sport            Event
1936 Summer Aeronautics      Aeronautics Mixed Aeronautics                       Berlin
            Alpinism         Alpinism Mixed Alpinism                             Berlin
                             Alpinism Mixed Alpinism                             Berlin
            Art Competitions Art Competitions Mixed Architecture, Architectu...  Berlin
                             Art Competitions Mixed Architecture, Architectu...  Berlin
...                                                                                 ...
2000 Summer Wrestling        Wrestling Men's Welterweight, Greco-Roman           Sydney
                             Wrestling Men's Welterweight, Greco-Roman           Sydney
                             Wrestling Men's Welterweight, Greco-Roman           Sydney
                             Wrestling Men's Welterweight, Greco-Roman           Sydney
                             Wrestling Men's Welterweight, Greco-Roman           Sydney

                                                                                Medal
Year Season Sport            Event
1936 Summer Aeronautics      Aeronautics Mixed Aeronautics                       Gold
            Alpinism         Alpinism Mixed Alpinism                             Gold
                             Alpinism Mixed Alpinism                             Gold
            Art Competitions Art Competitions Mixed Architecture, Architectu...   NaN
                             Art Competitions Mixed Architecture, Architectu...   NaN
...                                                                               ...
2000 Summer Wrestling        Wrestling Men's Welterweight, Greco-Roman            NaN
                             Wrestling Men's Welterweight, Greco-Roman            NaN
                             Wrestling Men's Welterweight, Greco-Roman            NaN
                             Wrestling Men's Welterweight, Greco-Roman            NaN
                             Wrestling Men's Welterweight, Greco-Roman            NaN

[138922 rows x 5 columns]

In [6]:
# What team has won the most medals in all archery events?

winners_only = df.dropna(subset=['Medal'])

winners_only.loc[slice(None), slice(None), 'Archery']['Team'].value_counts()

Team
South Korea           69
Belgium               52
France                48
United States         41
China                 19
Italy                 15
Great Britain         13
Netherlands            9
Chinese Taipei         9
Cincinnati Archers     8
Ukraine                8
Soviet Union           7
Japan                  7
Germany                7
Finland                6
Australia              5
Boston Archers         4
Potomac Archers        4
Poland                 4
Unified Team           4
Russia                 4
Indonesia              3
Spain                  3
Sweden                 2
Mexico                 2
Name: count, dtype: int64

In [7]:
# Starting in 1980, what is the average height of the “Table Tennis Women’s Team” event?

df.loc[(slice(1980, None), slice(None), slice(None), "Table Tennis Women's Team")]['Height'].mean()

np.float64(165.04827586206898)

In [8]:
# Starting in 1980, what is the average height of
# both “Table Tennis Women’s Team” and “Table Tennis Men’s Team”?

df.loc[(slice(1980, None), slice(None), slice(None), ["Table Tennis Women's Team", "Table Tennis Men's Team"])]['Height'].mean()

np.float64(171.26643598615917)

In [9]:
# How tall was the tallest-ever tennis player in Olympic games from 1980 until 2016?

df.loc[(slice(1980, 2016), slice(None), 'Tennis', slice(None))]['Height'].max()

np.float64(208.0)

### Going deep part from the book

In [10]:
df.xs(("Summer", "Table Tennis Women's Team"), level=['Season', 'Event'])['Height'].mean()

np.float64(165.04827586206898)

In [11]:
df.xs("Table Tennis Women's Team", level='Event')['Height'].mean()

np.float64(165.04827586206898)

#### Beyond the exercise_1

##### Events occur in either summer or winter Olympic games, but not both. As a result, the "Season" level in our multi-index is often unnecessary. Remove the "Season" level, and then find (again) the height of the tallest tennis player between 1980 and 2016.

In [12]:
df = df.droplevel('Season')

In [13]:
from pandas import IndexSlice as idx

df.loc[idx[1980:2016, 'Tennis'], 'Height'].max()

np.float64(208.0)

#### Beyond the exercise_2

##### In which city were the most gold medals awarded from 1980 onward?

In [14]:
selected_years = df.loc[idx[1980:]]

gold_medals = selected_years[selected_years['Medal'] == 'Gold']['City'].value_counts().head(1)

print(gold_medals)

City
Beijing    671
Name: count, dtype: int64

#### Beyond the exercise_3
#### How many gold medals were received by the United States since 1980? (Use the index to select the values.)

In [15]:
df.loc[idx[1980:]].loc[lambda x: (x['Medal'] == 'Gold') & (x['Team'] == 'United States'), 'Medal'].value_counts()

Medal
Gold    1257
Name: count, dtype: int64