In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/nyc_taxi_2019-01.csv',
     engine = 'pyarrow',
    dtype_backend = 'pyarrow',
    usecols = ['passenger_count', 'trip_distance', 'total_amount'] 
)

In [3]:
# Using a descending sort, find the average cost of the 20 longest (in distance) taxi
# rides in January 2019.

round(df.sort_values(by='trip_distance', ascending = False).head(20)['total_amount'].mean(), 2)

290.01

In [4]:
# Using an ascending sort, find the average cost of the 20 longest (in distance) taxi
# rides in January 2019. Are the results any different?

round(df.sort_values(by='trip_distance').tail(20)['total_amount'].mean(), 2)

290.01

In [5]:
# Sort by ascending passenger count and descending trip distance. (So, start with
# the longest trip with 0 passengers and end with the shortest trip with 9 passengers.)
# What is the average price paid for the top 50 rides?

(
    df
    .sort_values(by = ['passenger_count', 'trip_distance'], ascending = [True, False])
    .iloc[:50]['total_amount'].mean()
)

135.49739999999997

#### Beyond the exercise_1
##### In which five rides did people pay the most per mile? How far did people go on those trips?

In [6]:
df['mile_price'] = df['total_amount'] / df['trip_distance']
df

         passenger_count  trip_distance  total_amount  mile_price
0                      1            1.5          9.95    6.633333
1                      1            2.6          16.3    6.269231
2                      3            0.0           5.8         inf
3                      5            0.0          7.55         inf
4                      5            0.0         55.55         inf
...                  ...            ...           ...         ...
7667787                1           4.79         23.16    4.835073
7667788                1            0.0           0.0        <NA>
7667789                1            0.0           0.0        <NA>
7667790                1            0.0           0.0        <NA>
7667791                1            0.0           0.0        <NA>

[7667792 rows x 4 columns]

In [7]:
df['mile_price'] = df['total_amount']
df.loc[df['trip_distance'] > 0, 'mile_price'] = df['total_amount'] / df['trip_distance']

df.sort_values(by = 'mile_price', ascending = False).head(5)

         passenger_count  trip_distance  total_amount     mile_price
5323430                1            0.0     356214.78      356214.78
2499600                1            2.4     623261.66  259692.358333
478791                 1            0.1       6667.45        66674.5
7099014                4           0.01         415.3        41530.0
2159909                0            0.0       36090.3        36090.3

#### Beyond the exercise_2
##### Let’s assume that multipassenger rides are split evenly among the passengers. Given that assumption, in which 10 multipassenger rides did each individual pay the greatest amount?

In [8]:
df['cost_per_person'] = df['total_amount'] / df['passenger_count']
df.loc[df['passenger_count'] > 1].sort_values(by = 'cost_per_person', ascending = False).head(10)

,passenger_count,trip_distance,total_amount,mile_price,cost_per_person
2972145,2,19.9,589.96,29.646231,294.98
3014027,2,16.6,560.76,33.780723,280.38
3842620,2,110.04,515.82,4.687568,257.91
7593395,2,83.61,449.32,5.373998,224.66
149362,2,17.2,426.8,24.813953,213.4
5726185,2,65.05,416.82,6.407686,208.41
6857368,2,0.0,411.36,411.36,205.68
6496403,2,0.0,410.95,410.95,205.475
4751745,2,100.78,403.5,4.003771,201.75
1154626,2,0.0,400.8,400.8,200.4

#### Beyond the exercise_3
##### In the exercise solution, I showed that we needed to use `iloc` or `head`/`tail` to retrieve the first/last 20 rows because the index was scrambled after our sort operation. But you can pass `ignore_index=True` to `sort_values`: then the resulting data frame has a numeric index starting at 0. Use this option and `loc` to get the mean `total_amount` for the 20 longest trips.

In [9]:
(
    df.sort_values('trip_distance', ascending=False, ignore_index= True)['total_amount'].loc[:19].mean()
)

290.01

In [10]:
# NOTE: this was my original code solution for the base task
df.sort_values(by='trip_distance', ascending = False).head(20)['total_amount'].mean()

290.01