In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv(
    '../../../data/nyc_taxi_2019-01.csv',
     engine = 'pyarrow',
    dtype_backend = 'pyarrow',
    usecols = ['passenger_count', 'trip_distance', 'total_amount'] 
)

In [3]:
# Using a descending sort, find the average cost of the 20 longest (in distance) taxi
# rides in January 2019.

round(df.sort_values(by='trip_distance', ascending = False).head(20)['total_amount'].mean(), 2)

290.01

In [4]:
# Using an ascending sort, find the average cost of the 20 longest (in distance) taxi
# rides in January 2019. Are the results any different?

round(df.sort_values(by='trip_distance').tail(20)['total_amount'].mean(), 2)

290.01

In [5]:
# Sort by ascending passenger count and descending trip distance. (So, start with
# the longest trip with 0 passengers and end with the shortest trip with 9 passengers.)
# What is the average price paid for the top 50 rides?

(
    df
    .sort_values(by = ['passenger_count', 'trip_distance'], ascending = [True, False])
    .iloc[:50]['total_amount'].mean()
)

135.49739999999997

#### Beyond the exercise_1
##### In which five rides did people pay the most per mile? How far did people go on those trips?

In [6]:
df['mile_price'] = df['total_amount'] / df['trip_distance']
df

         passenger_count  trip_distance  total_amount  mile_price
0                      1            1.5          9.95    6.633333
1                      1            2.6          16.3    6.269231
2                      3            0.0           5.8         inf
3                      5            0.0          7.55         inf
4                      5            0.0         55.55         inf
...                  ...            ...           ...         ...
7667787                1           4.79         23.16    4.835073
7667788                1            0.0           0.0        <NA>
7667789                1            0.0           0.0        <NA>
7667790                1            0.0           0.0        <NA>
7667791                1            0.0           0.0        <NA>

[7667792 rows x 4 columns]

In [7]:
df['mile_price'] = df['total_amount']
df.loc[df['trip_distance'] > 0, 'mile_price'] = df['total_amount'] / df['trip_distance']

df.sort_values(by = 'mile_price', ascending = False).head(5)

         passenger_count  trip_distance  total_amount     mile_price
5323430                1            0.0     356214.78      356214.78
2499600                1            2.4     623261.66  259692.358333
478791                 1            0.1       6667.45        66674.5
7099014                4           0.01         415.3        41530.0
2159909                0            0.0       36090.3        36090.3