In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

#### In this exercise, I want you to create the same two-column data frame as in the last exercise. Then, update the values in the temp column so that any value less than 0 is set to 0.

In [2]:
s = pd.read_csv('../../../data/nyc-temps.txt', header = None, names = ['temp']).squeeze()

hours = np.arange(0, 24, 3)

df = pd.DataFrame({
    'temp' : s,
    'hour' : np.tile(hours, len(s) // len(hours) +1)[:len(s)]
})

df.loc[df['temp'] < 0, 'temp'] = 0

### Beyond the exercise_1

In [3]:
# Set all the odd temperatures to the mean of all the temperatures.

df = pd.DataFrame({
    'temp' : s,
    'hour' : np.tile(hours, len(s) // len(hours) +1)[:len(s)]
})

df['temp'] = df['temp'].astype(float)

mean_temp = df['temp'].mean()

df.loc[df['temp'] % 2 != 0, 'temp'] = mean_temp

df.head(20)

        temp  hour
0  -1.050754     0
1  -1.050754     3
2  -1.050754     6
3  -1.050754     9
4  -1.050754    12
5  -1.050754    15
6  -1.050754    18
7  -1.050754    21
8  -1.050754     0
9  -1.050754     3
10 -1.050754     6
11 -1.050754     9
12 -1.050754    12
13 -1.050754    15
14 -1.050754    18
15 -1.050754    21
16 -1.050754     0
17 -1.050754     3
18 -1.050754     6
19 -1.050754     9

### Beyond the exercise_2

In [4]:
# Set the even temperatures at hours 9 and 18 to 3.

df = pd.DataFrame({
    'temp' : s,
    'hour' : np.tile(hours, len(s) // len(hours) +1)[:len(s)]
})

df.loc[df['temp'] < 0, 'temp'] = 0

df.loc[(df['temp'] % 2 == 0) & (df['hour'].isin([9, 18])), 'temp'] = 3

### Beyond the exercise_3

In [5]:
# If the hour is odd, set the temperature to 5.

df = pd.DataFrame({
    'temp' : s,
    'hour' : np.tile(hours, len(s) // len(hours) +1)[:len(s)]
})

df.loc[df['temp'] < 0, 'temp'] = 0

df.loc[(df['hour'] % 2 != 0) , 'temp'] = 5

df

     temp  hour
0       0     0
1       5     3
2       0     6
3       5     9
4       0    12
..    ...   ...
724     2    12
725     5    15
726     2    18
727     5    21
728     2     0

[729 rows x 2 columns]