In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [4]:
df = pd.read_csv(
    '../../../data/linux-etc-passwd.txt',
    sep= ':',
    header= None,
    names= ['username', 'password', 'userid', 'groupid', 'name', 'homedir', 'shell'],
    index_col= 'username',
    comment= '#'
)

In [5]:
df

,password,userid,groupid,name,homedir,shell
username,,,,,,
root,x,0,0,root,/root,/bin/bash
daemon,x,1,1,daemon,/usr/sbin,/usr/sbin/nologin
bin,x,2,2,bin,/bin,/usr/sbin/nologin
sys,x,3,3,sys,/dev,/usr/sbin/nologin
sync,x,4,65534,sync,/bin,/bin/sync
games,x,5,60,games,/usr/games,/usr/sbin/nologin
man,x,6,12,man,/var/cache/man,/usr/sbin/nologin
lp,x,7,7,lp,/var/spool/lpd,/usr/sbin/nologin
mail,x,8,8,mail,/var/mail,/usr/sbin/nologin
news,x,9,9,news,/var/spool/news,/usr/sbin/nologin
uucp,x,10,10,uucp,/var/spool/uucp,/usr/sbin/nologin
proxy,x,13,13,proxy,/bin,/usr/sbin/nologin
www-data,x,33,33,www-data,/var/www,/usr/sbin/nologin
backup,x,34,34,backup,/var/backups,/usr/sbin/nologin
list,x,38,38,Mailing List Manager,/var/list,/usr/sbin/nologin
irc,x,39,39,ircd,/var/run/ircd,/usr/sbin/nologin
gnats,x,41,41,Gnats Bug-Reporting System (admin),/var/lib/gnats,/usr/sbin/nologin
nobody,x,65534,65534,nobody,/nonexistent,/usr/sbin/nologin
syslog,x,101,104,NaN,/home/syslog,/bin/false
messagebus,x,102,106,NaN,/var/run/dbus,/bin/false
landscape,x,103,109,NaN,/var/lib/landscape,/bin/false
jci,x,955,955,NaN,/home/jci,/bin/bash
sshd,x,104,65534,NaN,/var/run/sshd,/usr/sbin/nologin
user,x,1000,1000,"user,,,",/home/user,/bin/bash
reuven,x,1001,1001,"Reuven M. Lerner,,,",/home/reuven,/bin/bash
postfix,x,105,113,NaN,/var/spool/postfix,/bin/false
colord,x,106,116,"colord colour management daemon,,,",/var/lib/colord,/bin/false
postgres,x,107,117,"PostgreSQL administrator,,,",/var/lib/postgresql,/bin/bash
dovecot,x,108,119,"Dovecot mail server,,,",/usr/lib/dovecot,/bin/false
dovenull,x,109,120,"Dovecot login user,,,",/nonexistent,/bin/false
postgrey,x,110,121,NaN,/var/lib/postgrey,/bin/false
debian-spamd,x,111,122,NaN,/var/lib/spamassassin,/bin/sh
memcache,x,113,124,"Memcached,,,",/nonexistent,/bin/false
genadi,x,1002,1003,"Genadi Reznichenko,,,",/home/genadi,/bin/bash
shira,x,1003,1004,"Shira Friedman,,,",/home/shira,/bin/bash
atara,x,1004,1005,"Atara Lerner-Friedman,,,",/home/atara,/bin/bash
shikma,x,1005,1006,"Shikma Lerner-Friedman,,,",/home/shikma,/bin/bash
amotz,x,1006,1007,"Amotz Lerner-Friedman,,,",/home/amotz,/bin/bash
mysql,x,114,125,"MySQL Server,,,",/nonexistent,/bin/false
clamav,x,115,126,NaN,/var/lib/clamav,/bin/false
amavis,x,116,127,"AMaViS system user,,,",/var/lib/amavis,/bin/sh
opendkim,x,117,128,NaN,/var/run/opendkim,/bin/false
gitlab-redis,x,999,1009,NaN,/var/opt/gitlab/redis,/bin/nologin
gitlab-psql,x,998,1010,NaN,/var/opt/gitlab/postgresql,/bin/sh
git,x,1007,1008,"GitLab,,,",/home/git,/bin/bash
opendmarc,x,118,129,NaN,/var/run/opendmarc,/bin/false
dkim-milter-python,x,119,130,NaN,/var/run/dkim-milter-python,/bin/false
deploy,x,1008,1011,"Deploy,,,",/home/deploy,/bin/bash
redis,x,112,123,"redis server,,,",/var/lib/redis,/bin/false

### Beyond the exercise_1
####  Ignore the `password` and `groupid` fields so they don’t appear in the data frame.

In [10]:
df = pd.read_csv(
    '../../../data/linux-etc-passwd.txt',
    sep= ':',
    header= None,
    names= ['username', 'userid', 'name', 'homedir', 'shell'],
    index_col= 'username',
    usecols= [0, 2, 4, 5, 6],
    comment= '#'
)

In [11]:
df

,userid,name,homedir,shell
username,,,,
root,0,root,/root,/bin/bash
daemon,1,daemon,/usr/sbin,/usr/sbin/nologin
bin,2,bin,/bin,/usr/sbin/nologin
sys,3,sys,/dev,/usr/sbin/nologin
sync,4,sync,/bin,/bin/sync
games,5,games,/usr/games,/usr/sbin/nologin
man,6,man,/var/cache/man,/usr/sbin/nologin
lp,7,lp,/var/spool/lpd,/usr/sbin/nologin
mail,8,mail,/var/mail,/usr/sbin/nologin
news,9,news,/var/spool/news,/usr/sbin/nologin
uucp,10,uucp,/var/spool/uucp,/usr/sbin/nologin
proxy,13,proxy,/bin,/usr/sbin/nologin
www-data,33,www-data,/var/www,/usr/sbin/nologin
backup,34,backup,/var/backups,/usr/sbin/nologin
list,38,Mailing List Manager,/var/list,/usr/sbin/nologin
irc,39,ircd,/var/run/ircd,/usr/sbin/nologin
gnats,41,Gnats Bug-Reporting System (admin),/var/lib/gnats,/usr/sbin/nologin
nobody,65534,nobody,/nonexistent,/usr/sbin/nologin
syslog,101,NaN,/home/syslog,/bin/false
messagebus,102,NaN,/var/run/dbus,/bin/false
landscape,103,NaN,/var/lib/landscape,/bin/false
jci,955,NaN,/home/jci,/bin/bash
sshd,104,NaN,/var/run/sshd,/usr/sbin/nologin
user,1000,"user,,,",/home/user,/bin/bash
reuven,1001,"Reuven M. Lerner,,,",/home/reuven,/bin/bash
postfix,105,NaN,/var/spool/postfix,/bin/false
colord,106,"colord colour management daemon,,,",/var/lib/colord,/bin/false
postgres,107,"PostgreSQL administrator,,,",/var/lib/postgresql,/bin/bash
dovecot,108,"Dovecot mail server,,,",/usr/lib/dovecot,/bin/false
dovenull,109,"Dovecot login user,,,",/nonexistent,/bin/false
postgrey,110,NaN,/var/lib/postgrey,/bin/false
debian-spamd,111,NaN,/var/lib/spamassassin,/bin/sh
memcache,113,"Memcached,,,",/nonexistent,/bin/false
genadi,1002,"Genadi Reznichenko,,,",/home/genadi,/bin/bash
shira,1003,"Shira Friedman,,,",/home/shira,/bin/bash
atara,1004,"Atara Lerner-Friedman,,,",/home/atara,/bin/bash
shikma,1005,"Shikma Lerner-Friedman,,,",/home/shikma,/bin/bash
amotz,1006,"Amotz Lerner-Friedman,,,",/home/amotz,/bin/bash
mysql,114,"MySQL Server,,,",/nonexistent,/bin/false
clamav,115,NaN,/var/lib/clamav,/bin/false
amavis,116,"AMaViS system user,,,",/var/lib/amavis,/bin/sh
opendkim,117,NaN,/var/run/opendkim,/bin/false
gitlab-redis,999,NaN,/var/opt/gitlab/redis,/bin/nologin
gitlab-psql,998,NaN,/var/opt/gitlab/postgresql,/bin/sh
git,1007,"GitLab,,,",/home/git,/bin/bash
opendmarc,118,NaN,/var/run/opendmarc,/bin/false
dkim-milter-python,119,NaN,/var/run/dkim-milter-python,/bin/false
deploy,1008,"Deploy,,,",/home/deploy,/bin/bash
redis,112,"redis server,,,",/var/lib/redis,/bin/false

### Beyond the exercise_2
####  Unix systems typically reserve user IDs below 1000 to special accounts. Show the nonspecial usernames in this passwd file.

In [21]:
list(df[df['userid'] > 999].index)

['nobody',
 'user',
 'reuven',
 'genadi',
 'shira',
 'atara',
 'shikma',
 'amotz',
 'git',
 'deploy']

### Beyond the exercise_3
####  Immediately after logging into a Unix system, a command interpreter known as a `shell` fires up. What are the different shells in this file?

In [22]:
df['shell'].value_counts()

shell
/usr/sbin/nologin    17
/bin/false           15
/bin/bash            12
/bin/sh               3
/bin/sync             1
/bin/nologin          1
Name: count, dtype: int64

In [ ]:
#  NOTE: below is Reuven answer to this exercise:

# The `unique` method does this for us, returning a NumPy array -- but Pandas offers its own
# drop_duplicates method, which keeps us with a series

df['shell'].drop_duplicates()